// The /reference command library. Each entry maps to an archetype animation (archetypes.ts)
// + params, so coverage grows by adding data, not code. `exampleId` (when set) links to a
// runnable Playground example. OpenACC entries are a planned follow-up (the Tech type allows it).
import type { ArchetypeParams } from "./archetypes";

export type Tech = "OpenMP" | "MPI" | "OpenACC";

export type RefEntry = {
  id: string;
  tech: Tech;
  category: string;
  name: string;        // the directive / call as written
  signature: string;   // canonical syntax
  summary: string;     // one-sentence plain-English meaning
  note?: string;       // short "good to know" / when-to-use / gotcha
  visual: { archetype: string; params?: ArchetypeParams };
  exampleId?: string;  // a Playground example id (-> /playground?ex=...)
  related?: string[];  // other entry ids
};

export const ENTRIES: RefEntry[] = [
  /* ===================== OpenMP ===================== */
  {
    id: "omp_parallel", tech: "OpenMP", category: "Parallel regions", name: "#pragma omp parallel",
    signature: "#pragma omp parallel [clauses]\n{ /* each thread runs this */ }",
    summary: "Forks a team of threads that all run the enclosed block; they join at the end.",
    note: "By itself every thread runs the WHOLE block — add a work-sharing construct (for/sections) to split work.",
    visual: { archetype: "forkJoin", params: { threads: 6 } }, exampleId: "hello",
    related: ["omp_for", "omp_get_thread_num"],
  },
  {
    id: "omp_get_thread_num", tech: "OpenMP", category: "Parallel regions", name: "omp_get_thread_num()",
    signature: "int id = omp_get_thread_num();",
    summary: "Returns the calling thread's id within its team (0 .. num_threads-1).",
    visual: { archetype: "forkJoin", params: { threads: 6 } }, related: ["omp_get_num_threads", "omp_parallel"],
  },
  {
    id: "omp_get_num_threads", tech: "OpenMP", category: "Parallel regions", name: "omp_get_num_threads()",
    signature: "int n = omp_get_num_threads();",
    summary: "Returns how many threads are in the current team.",
    note: "Outside a parallel region it returns 1. For the max, use omp_get_max_threads().",
    visual: { archetype: "forkJoin", params: { threads: 6 } }, related: ["omp_get_thread_num"],
  },
  {
    id: "omp_set_num_threads", tech: "OpenMP", category: "Parallel regions", name: "omp_set_num_threads(n)",
    signature: "omp_set_num_threads(8);",
    summary: "Sets how many threads the next parallel region should use.",
    note: "Or set it per-region with `num_threads(n)`, or globally with the OMP_NUM_THREADS env var.",
    visual: { archetype: "forkJoin", params: { threads: 8 } }, related: ["env_omp_num_threads"],
  },
  {
    id: "env_omp_num_threads", tech: "OpenMP", category: "Parallel regions", name: "OMP_NUM_THREADS",
    signature: "export OMP_NUM_THREADS=8   # environment variable",
    summary: "Environment variable choosing the default team size — no recompile needed.",
    visual: { archetype: "forkJoin", params: { threads: 8 } }, related: ["omp_set_num_threads"],
  },
  {
    id: "omp_parallel_for", tech: "OpenMP", category: "Work-sharing", name: "#pragma omp parallel for",
    signature: "#pragma omp parallel for\nfor (i = 0; i < N; i++) work(i);",
    summary: "Shorthand for a parallel region + a for-construct: splits the loop across threads.",
    note: "The most common OpenMP line. Loop iterations must be independent.",
    visual: { archetype: "worksharing", params: { kind: "for", threads: 4 } }, exampleId: "reduction",
    related: ["omp_for", "omp_parallel"],
  },
  {
    id: "omp_for", tech: "OpenMP", category: "Work-sharing", name: "#pragma omp for",
    signature: "#pragma omp parallel\n{ #pragma omp for\n  for (...) work(i); }",
    summary: "Inside a parallel region, divides the loop's iterations among the existing team.",
    visual: { archetype: "worksharing", params: { kind: "for", threads: 4 } }, exampleId: "reduction",
    related: ["omp_parallel_for", "omp_schedule_static"],
  },
  {
    id: "omp_sections", tech: "OpenMP", category: "Work-sharing", name: "#pragma omp sections",
    signature: "#pragma omp sections\n{ #pragma omp section\n  taskA();\n  #pragma omp section\n  taskB(); }",
    summary: "Runs each independent code section once, on a different thread (functional parallelism).",
    visual: { archetype: "worksharing", params: { kind: "sections" } }, related: ["omp_for", "omp_task"],
  },
  {
    id: "omp_single", tech: "OpenMP", category: "Work-sharing", name: "#pragma omp single",
    signature: "#pragma omp single\n{ /* run by exactly one thread */ }",
    summary: "Exactly one thread (any one) runs the block; the others skip it.",
    note: "There's an implicit barrier at the end (use `nowait` to drop it).",
    visual: { archetype: "worksharing", params: { kind: "single" } }, related: ["omp_master", "omp_barrier"],
  },
  {
    id: "omp_master", tech: "OpenMP", category: "Work-sharing", name: "#pragma omp master",
    signature: "#pragma omp master\n{ /* run only by thread 0 */ }",
    summary: "Only the master thread (id 0) runs the block; no implicit barrier.",
    visual: { archetype: "worksharing", params: { kind: "master" } }, related: ["omp_single"],
  },
  {
    id: "omp_schedule_static", tech: "OpenMP", category: "Scheduling", name: "schedule(static)",
    signature: "#pragma omp for schedule(static[,chunk])",
    summary: "Splits iterations into equal contiguous chunks decided up front — lowest overhead.",
    note: "Best when every iteration costs about the same.",
    visual: { archetype: "schedule", params: { kind: "static" } }, related: ["omp_schedule_dynamic", "omp_schedule_guided"],
  },
  {
    id: "omp_schedule_dynamic", tech: "OpenMP", category: "Scheduling", name: "schedule(dynamic)",
    signature: "#pragma omp for schedule(dynamic[,chunk])",
    summary: "Threads grab small chunks on demand as they finish — balances uneven work.",
    note: "Fixes load imbalance, but the hand-out has overhead; tune the chunk size.",
    visual: { archetype: "schedule", params: { kind: "dynamic" } }, related: ["omp_schedule_static", "omp_schedule_guided"],
  },
  {
    id: "omp_schedule_guided", tech: "OpenMP", category: "Scheduling", name: "schedule(guided)",
    signature: "#pragma omp for schedule(guided[,chunk])",
    summary: "Like dynamic but chunks start large and shrink — good balance with less overhead.",
    visual: { archetype: "schedule", params: { kind: "guided" } }, related: ["omp_schedule_dynamic"],
  },
  {
    id: "omp_collapse", tech: "OpenMP", category: "Scheduling", name: "collapse(n)",
    signature: "#pragma omp for collapse(2)\nfor (i..) for (j..) work(i,j);",
    summary: "Merges n perfectly-nested loops into one larger iteration space to parallelize.",
    note: "Use when the outer loop alone has too few iterations to fill the threads.",
    visual: { archetype: "worksharing", params: { kind: "for", threads: 4 } }, related: ["omp_parallel_for"],
  },
  {
    id: "omp_barrier", tech: "OpenMP", category: "Synchronization", name: "#pragma omp barrier",
    signature: "#pragma omp barrier",
    summary: "Every thread waits here until all threads in the team arrive.",
    visual: { archetype: "barrier", params: { kind: "barrier" } }, related: ["omp_nowait", "omp_taskwait"],
  },
  {
    id: "omp_nowait", tech: "OpenMP", category: "Synchronization", name: "nowait",
    signature: "#pragma omp for nowait",
    summary: "Removes the implicit barrier at the end of a work-sharing construct.",
    note: "Speeds things up, but only safe when later code doesn't depend on all iterations finishing.",
    visual: { archetype: "barrier", params: { kind: "nowait" } }, related: ["omp_barrier"],
  },
  {
    id: "omp_critical", tech: "OpenMP", category: "Synchronization", name: "#pragma omp critical",
    signature: "#pragma omp critical\n{ /* one thread at a time */ }",
    summary: "Makes the block mutually exclusive — only one thread executes it at a time.",
    note: "Correct but slow if hot: it serializes. Prefer reduction/atomic where possible.",
    visual: { archetype: "criticalAtomic", params: { kind: "critical" } }, exampleId: "sync", related: ["omp_atomic", "omp_reduction"],
  },
  {
    id: "omp_atomic", tech: "OpenMP", category: "Synchronization", name: "#pragma omp atomic",
    signature: "#pragma omp atomic\nsum += x;",
    summary: "A single memory update done atomically — cheaper than critical for one operation.",
    visual: { archetype: "criticalAtomic", params: { kind: "atomic" } }, exampleId: "sync", related: ["omp_critical", "omp_reduction"],
  },
  {
    id: "omp_locks", tech: "OpenMP", category: "Synchronization", name: "omp_set_lock / omp_unset_lock",
    signature: "omp_lock_t l; omp_init_lock(&l);\nomp_set_lock(&l); /* ... */ omp_unset_lock(&l);",
    summary: "Explicit locks for fine-grained mutual exclusion when critical isn't flexible enough.",
    visual: { archetype: "criticalAtomic", params: { kind: "lock" } }, related: ["omp_critical"],
  },
  {
    id: "omp_taskwait", tech: "OpenMP", category: "Synchronization", name: "#pragma omp taskwait",
    signature: "#pragma omp taskwait",
    summary: "Waits for the child tasks spawned by the current task to complete.",
    visual: { archetype: "barrier", params: { kind: "barrier" } }, related: ["omp_task"],
  },
  {
    id: "omp_shared", tech: "OpenMP", category: "Data sharing", name: "shared(var)",
    signature: "#pragma omp parallel shared(x)",
    summary: "All threads access the SAME variable — one copy in shared memory.",
    note: "Concurrent writes to a shared variable are a data race; guard them (reduction/atomic/critical).",
    visual: { archetype: "dataSharing", params: { clause: "shared" } }, exampleId: "falsesharing",
    related: ["omp_private", "omp_reduction"],
  },
  {
    id: "omp_private", tech: "OpenMP", category: "Data sharing", name: "private(var)",
    signature: "#pragma omp parallel private(x)",
    summary: "Each thread gets its own uninitialised copy of the variable.",
    visual: { archetype: "dataSharing", params: { clause: "private" } }, related: ["omp_firstprivate", "omp_shared"],
  },
  {
    id: "omp_firstprivate", tech: "OpenMP", category: "Data sharing", name: "firstprivate(var)",
    signature: "#pragma omp parallel firstprivate(x)",
    summary: "Private copies, each initialised from the variable's value before the region.",
    visual: { archetype: "dataSharing", params: { clause: "firstprivate" } }, related: ["omp_private", "omp_lastprivate"],
  },
  {
    id: "omp_lastprivate", tech: "OpenMP", category: "Data sharing", name: "lastprivate(var)",
    signature: "#pragma omp for lastprivate(x)",
    summary: "Private copies; the value from the last loop iteration is copied back out.",
    visual: { archetype: "dataSharing", params: { clause: "lastprivate" } }, related: ["omp_firstprivate"],
  },
  {
    id: "omp_reduction", tech: "OpenMP", category: "Data sharing", name: "reduction(op:var)",
    signature: "#pragma omp parallel for reduction(+:sum)",
    summary: "Each thread keeps a private partial; OpenMP combines them with op at the end.",
    note: "The safe, fast way to accumulate (sum, max, &&, ...) — no race, scales well.",
    visual: { archetype: "reduction", params: { threads: 4 } }, exampleId: "reduction",
    related: ["omp_critical", "omp_atomic"],
  },
  {
    id: "omp_default", tech: "OpenMP", category: "Data sharing", name: "default(none)",
    signature: "#pragma omp parallel default(none) shared(...) private(...)",
    summary: "Forces you to declare the sharing of every variable — catches mistakes early.",
    note: "A great habit: with default(none) the compiler errors on anything you forgot to classify.",
    visual: { archetype: "dataSharing", params: { clause: "shared" } }, related: ["omp_shared", "omp_private"],
  },
  {
    id: "omp_task", tech: "OpenMP", category: "Tasking", name: "#pragma omp task",
    signature: "#pragma omp task\n{ /* unit of deferred work */ }",
    summary: "Creates a task that any thread can run later — great for irregular/recursive work.",
    note: "Usually created inside a single region; combine with taskwait/depend to order them.",
    visual: { archetype: "tasks" }, related: ["omp_taskloop", "omp_taskwait"],
  },
  {
    id: "omp_taskloop", tech: "OpenMP", category: "Tasking", name: "#pragma omp taskloop",
    signature: "#pragma omp taskloop\nfor (...) work(i);",
    summary: "Turns a loop into a set of tasks the team picks up (work-stealing balance).",
    visual: { archetype: "tasks" }, related: ["omp_task", "omp_schedule_dynamic"],
  },
  {
    id: "omp_depend", tech: "OpenMP", category: "Tasking", name: "depend(in/out:var)",
    signature: "#pragma omp task depend(out:a)\n#pragma omp task depend(in:a)",
    summary: "Declares data dependencies so the runtime orders tasks correctly.",
    visual: { archetype: "tasks" }, related: ["omp_task"],
  },

  {
    id: "omp_num_threads_clause", tech: "OpenMP", category: "Parallel regions", name: "num_threads(n)",
    signature: "#pragma omp parallel num_threads(4)",
    summary: "Sets the team size for just this parallel region.",
    visual: { archetype: "forkJoin", params: { threads: 4 } }, related: ["omp_set_num_threads", "omp_parallel"],
  },
  {
    id: "omp_if_clause", tech: "OpenMP", category: "Parallel regions", name: "if(condition)",
    signature: "#pragma omp parallel if(n > 1000)",
    summary: "Only goes parallel when the condition holds — otherwise runs serially (no fork).",
    note: "Avoids paying thread-creation overhead on small inputs.",
    visual: { archetype: "forkJoin", params: { threads: 4 } }, related: ["omp_parallel"],
  },
  {
    id: "omp_get_max_threads", tech: "OpenMP", category: "Parallel regions", name: "omp_get_max_threads()",
    signature: "int n = omp_get_max_threads();",
    summary: "How many threads the next parallel region would use — valid even in serial code.",
    visual: { archetype: "forkJoin", params: { threads: 6 } }, related: ["omp_get_num_threads"],
  },
  {
    id: "omp_get_wtime", tech: "OpenMP", category: "Runtime", name: "omp_get_wtime()",
    signature: "double t0 = omp_get_wtime(); /* ... */ double s = omp_get_wtime() - t0;",
    summary: "High-resolution wall-clock seconds — wrap a region to time it.",
    visual: { archetype: "forkJoin", params: { threads: 6 } }, related: ["mpi_wtime"],
  },
  {
    id: "omp_parallel_sections", tech: "OpenMP", category: "Work-sharing", name: "#pragma omp parallel sections",
    signature: "#pragma omp parallel sections\n{ #pragma omp section ...\n  #pragma omp section ... }",
    summary: "Shorthand for a parallel region plus sections — run independent blocks concurrently.",
    visual: { archetype: "worksharing", params: { kind: "sections" } }, related: ["omp_sections"],
  },
  {
    id: "omp_simd", tech: "OpenMP", category: "Work-sharing", name: "#pragma omp simd",
    signature: "#pragma omp simd\nfor (i = 0; i < N; i++) a[i] = b[i] + c[i];",
    summary: "Vectorizes the loop — one core does several iterations at once with SIMD lanes.",
    note: "Different axis from threads: combine as `parallel for simd` to use both.",
    visual: { archetype: "worksharing", params: { kind: "for", threads: 4 } }, related: ["omp_parallel_for", "acc_vector"],
  },
  {
    id: "omp_schedule_runtime", tech: "OpenMP", category: "Scheduling", name: "schedule(runtime)",
    signature: "#pragma omp for schedule(runtime)   // set OMP_SCHEDULE at run time",
    summary: "Defers the schedule choice to the OMP_SCHEDULE environment variable — tune without recompiling.",
    visual: { archetype: "schedule", params: { kind: "dynamic" } }, related: ["omp_schedule_static", "omp_schedule_dynamic"],
  },
  {
    id: "omp_ordered", tech: "OpenMP", category: "Synchronization", name: "#pragma omp ordered",
    signature: "#pragma omp for ordered\nfor (...) { #pragma omp ordered\n  printf(...); }",
    summary: "Forces part of a parallel loop to run in iteration order (e.g. ordered output).",
    note: "Serializes that part — use sparingly.",
    visual: { archetype: "criticalAtomic", params: { kind: "critical" } }, related: ["omp_critical"],
  },
  {
    id: "omp_flush", tech: "OpenMP", category: "Synchronization", name: "#pragma omp flush",
    signature: "#pragma omp flush(var)",
    summary: "Makes a thread's view of memory consistent with others at that point.",
    note: "Rarely needed by hand — barriers/atomics flush for you.",
    visual: { archetype: "barrier", params: { kind: "barrier" } }, related: ["omp_barrier"],
  },
  {
    id: "omp_threadprivate", tech: "OpenMP", category: "Data sharing", name: "threadprivate(var)",
    signature: "static int counter;\n#pragma omp threadprivate(counter)",
    summary: "Gives each thread its own persistent copy of a global/static variable across regions.",
    visual: { archetype: "dataSharing", params: { clause: "private" } }, related: ["omp_private"],
  },
  {
    id: "omp_target", tech: "OpenMP", category: "Offloading (target)", name: "#pragma omp target",
    signature: "#pragma omp target\n{ /* runs on the GPU/accelerator */ }",
    summary: "Offloads the region to an accelerator (GPU) — OpenMP's equivalent of OpenACC's parallel.",
    note: "Pair with map(...) to move data and teams/distribute to spread work.",
    visual: { archetype: "offload", params: { kind: "parallel" } }, related: ["omp_map", "omp_teams", "acc_parallel"],
  },
  {
    id: "omp_target_data", tech: "OpenMP", category: "Offloading (target)", name: "#pragma omp target data",
    signature: "#pragma omp target data map(tofrom: a[0:N])\n{ /* several target regions reuse a */ }",
    summary: "Keeps data resident on the device across multiple target regions (like acc data).",
    visual: { archetype: "accData", params: { clause: "copy" } }, related: ["omp_map", "acc_data"],
  },
  {
    id: "omp_map", tech: "OpenMP", category: "Offloading (target)", name: "map(to/from/tofrom: a)",
    signature: "#pragma omp target map(to: a[0:N]) map(from: r[0:N])",
    summary: "Controls host↔device data movement: to (in), from (out), tofrom (both), alloc (no copy).",
    visual: { archetype: "accData", params: { clause: "copy" } }, related: ["omp_target_data", "acc_copyin"],
  },
  {
    id: "omp_teams", tech: "OpenMP", category: "Offloading (target)", name: "#pragma omp teams",
    signature: "#pragma omp target teams\n{ /* a league of teams on the device */ }",
    summary: "Creates a league of thread teams on the accelerator (≈ OpenACC gangs / CUDA blocks).",
    visual: { archetype: "offload", params: { kind: "loop" } }, related: ["omp_distribute", "acc_gang"],
  },
  {
    id: "omp_distribute", tech: "OpenMP", category: "Offloading (target)", name: "#pragma omp distribute",
    signature: "#pragma omp target teams distribute parallel for\nfor (...) work(i);",
    summary: "The full offload combo: spread loop iterations across teams, then threads, on the device.",
    visual: { archetype: "offload", params: { kind: "loop" } }, related: ["omp_teams", "acc_parallel_loop"],
  },

  /* ===================== MPI ===================== */
  {
    id: "mpi_init", tech: "MPI", category: "Setup", name: "MPI_Init / MPI_Finalize",
    signature: "MPI_Init(&argc, &argv);\n/* ... */\nMPI_Finalize();",
    summary: "Start and stop the MPI runtime; bracket every MPI program with these.",
    visual: { archetype: "ranksMemory", params: { threads: 4 } }, related: ["mpi_comm_rank", "mpi_comm_size"],
  },
  {
    id: "mpi_comm_rank", tech: "MPI", category: "Setup", name: "MPI_Comm_rank",
    signature: "int rank; MPI_Comm_rank(MPI_COMM_WORLD, &rank);",
    summary: "Gives this process its id (0 .. size-1) within a communicator.",
    note: "Branch on rank to make different processes do different things.",
    visual: { archetype: "ranksMemory", params: { threads: 4 } }, related: ["mpi_comm_size", "mpi_init"],
  },
  {
    id: "mpi_comm_size", tech: "MPI", category: "Setup", name: "MPI_Comm_size",
    signature: "int size; MPI_Comm_size(MPI_COMM_WORLD, &size);",
    summary: "Returns how many processes (ranks) are in the communicator.",
    visual: { archetype: "ranksMemory", params: { threads: 4 } }, related: ["mpi_comm_rank"],
  },
  {
    id: "mpi_comm_split", tech: "MPI", category: "Setup", name: "MPI_Comm_split",
    signature: "MPI_Comm_split(MPI_COMM_WORLD, color, key, &newcomm);",
    summary: "Partitions ranks into sub-communicators by `color` — independent groups.",
    visual: { archetype: "ranksMemory", params: { threads: 6, kind: "split" } }, related: ["mpi_comm_rank"],
  },
  {
    id: "mpi_wtime", tech: "MPI", category: "Setup", name: "MPI_Wtime",
    signature: "double t = MPI_Wtime();",
    summary: "High-resolution wall-clock seconds — wrap a region to time it.",
    note: "Pair with MPI_Reduce(MAX) to get the slowest rank's time (the true wall time).",
    visual: { archetype: "ranksMemory", params: { threads: 4 } }, related: ["mpi_reduce"],
  },
  {
    id: "mpi_send", tech: "MPI", category: "Point-to-point", name: "MPI_Send",
    signature: "MPI_Send(&x, n, MPI_INT, dest, tag, comm);",
    summary: "Sends a message to one specific rank (blocking: returns when the buffer is reusable).",
    visual: { archetype: "pointToPoint", params: { mode: "blocking" } }, related: ["mpi_recv", "mpi_isend"],
  },
  {
    id: "mpi_recv", tech: "MPI", category: "Point-to-point", name: "MPI_Recv",
    signature: "MPI_Recv(&x, n, MPI_INT, src, tag, comm, &status);",
    summary: "Receives a message from a rank (blocks until the message arrives).",
    note: "Send/Recv tags and types must match, or you'll deadlock or mis-read.",
    visual: { archetype: "pointToPoint", params: { mode: "blocking" } }, related: ["mpi_send", "mpi_sendrecv"],
  },
  {
    id: "mpi_sendrecv", tech: "MPI", category: "Point-to-point", name: "MPI_Sendrecv",
    signature: "MPI_Sendrecv(sbuf,.., dest,.., rbuf,.., src,.., comm, &st);",
    summary: "Send and receive in one call — avoids deadlock in exchanges (e.g. halo swaps).",
    visual: { archetype: "pointToPoint", params: { mode: "blocking" } }, related: ["mpi_send", "mpi_recv"],
  },
  {
    id: "mpi_isend", tech: "MPI", category: "Point-to-point", name: "MPI_Isend / MPI_Irecv",
    signature: "MPI_Isend(&x, n, .., &req);  /* ... compute ... */\nMPI_Wait(&req, &status);",
    summary: "Non-blocking: post the transfer, keep computing, then Wait — overlaps comm with compute.",
    note: "The key to hiding communication cost. Don't touch the buffer until Wait returns.",
    visual: { archetype: "pointToPoint", params: { mode: "nonblocking" } }, related: ["mpi_wait", "mpi_send"],
  },
  {
    id: "mpi_wait", tech: "MPI", category: "Point-to-point", name: "MPI_Wait / MPI_Waitall",
    signature: "MPI_Wait(&req, &status);  MPI_Waitall(n, reqs, stats);",
    summary: "Blocks until one (or all) non-blocking operations complete.",
    visual: { archetype: "pointToPoint", params: { mode: "nonblocking" } }, related: ["mpi_isend"],
  },
  {
    id: "mpi_bcast", tech: "MPI", category: "Collectives", name: "MPI_Bcast",
    signature: "MPI_Bcast(&buf, n, type, root, comm);",
    summary: "The root sends the same data to every rank in the communicator.",
    visual: { archetype: "collective", params: { op: "bcast" } }, related: ["mpi_scatter", "mpi_reduce"],
  },
  {
    id: "mpi_scatter", tech: "MPI", category: "Collectives", name: "MPI_Scatter",
    signature: "MPI_Scatter(send, n, .., recv, n, .., root, comm);",
    summary: "The root splits an array and sends one chunk to each rank.",
    visual: { archetype: "collective", params: { op: "scatter" } }, related: ["mpi_gather", "mpi_bcast"],
  },
  {
    id: "mpi_gather", tech: "MPI", category: "Collectives", name: "MPI_Gather",
    signature: "MPI_Gather(send, n, .., recv, n, .., root, comm);",
    summary: "Collects one piece from each rank into an array at the root (inverse of scatter).",
    visual: { archetype: "collective", params: { op: "gather" } }, related: ["mpi_scatter", "mpi_allgather"],
  },
  {
    id: "mpi_allgather", tech: "MPI", category: "Collectives", name: "MPI_Allgather",
    signature: "MPI_Allgather(send, n, .., recv, n, .., comm);",
    summary: "Like gather, but every rank ends up with the full collected array.",
    visual: { archetype: "collective", params: { op: "allgather" } }, related: ["mpi_gather"],
  },
  {
    id: "mpi_reduce", tech: "MPI", category: "Collectives", name: "MPI_Reduce",
    signature: "MPI_Reduce(send, recv, n, type, MPI_SUM, root, comm);",
    summary: "Combines values from all ranks with an op (sum, max, ...) into the root.",
    visual: { archetype: "collective", params: { op: "reduce" } }, related: ["mpi_allreduce", "mpi_gather"],
  },
  {
    id: "mpi_allreduce", tech: "MPI", category: "Collectives", name: "MPI_Allreduce",
    signature: "MPI_Allreduce(send, recv, n, type, MPI_SUM, comm);",
    summary: "Reduce, then give the result to every rank — extremely common (e.g. global sums).",
    visual: { archetype: "collective", params: { op: "allreduce" } }, related: ["mpi_reduce"],
  },
  {
    id: "mpi_alltoall", tech: "MPI", category: "Collectives", name: "MPI_Alltoall",
    signature: "MPI_Alltoall(send, n, .., recv, n, .., comm);",
    summary: "Every rank sends a distinct chunk to every other rank — a full transpose of data.",
    note: "The most communication-heavy collective; can dominate at scale (e.g. FFTs).",
    visual: { archetype: "collective", params: { op: "alltoall" } }, related: ["mpi_allgather"],
  },
  {
    id: "mpi_barrier", tech: "MPI", category: "Collectives", name: "MPI_Barrier",
    signature: "MPI_Barrier(comm);",
    summary: "No rank proceeds until all ranks in the communicator have reached the barrier.",
    visual: { archetype: "collective", params: { op: "barrier" } }, related: ["omp_barrier"],
  },

  {
    id: "mpi_probe", tech: "MPI", category: "Point-to-point", name: "MPI_Probe / MPI_Iprobe",
    signature: "MPI_Probe(src, tag, comm, &status);",
    summary: "Checks for an incoming message (and its size) before you receive it.",
    note: "Use with MPI_Get_count to size a buffer for an unknown-length message.",
    visual: { archetype: "pointToPoint", params: { mode: "blocking" } }, related: ["mpi_recv", "mpi_get_count"],
  },
  {
    id: "mpi_get_count", tech: "MPI", category: "Point-to-point", name: "MPI_Get_count",
    signature: "int n; MPI_Get_count(&status, MPI_INT, &n);",
    summary: "Reads how many elements a received (or probed) message actually contained.",
    visual: { archetype: "pointToPoint", params: { mode: "blocking" } }, related: ["mpi_probe", "mpi_recv"],
  },
  {
    id: "mpi_test", tech: "MPI", category: "Point-to-point", name: "MPI_Test",
    signature: "int done; MPI_Test(&req, &done, &status);",
    summary: "Non-blocking check: returns immediately, telling you whether the request finished.",
    note: "Lets you poll and do other work instead of blocking in MPI_Wait.",
    visual: { archetype: "pointToPoint", params: { mode: "nonblocking" } }, related: ["mpi_wait", "mpi_isend"],
  },
  {
    id: "mpi_scatterv", tech: "MPI", category: "Collectives", name: "MPI_Scatterv / MPI_Gatherv",
    signature: "MPI_Scatterv(send, counts, displs, .., recv, n, .., root, comm);",
    summary: "Like scatter/gather but with per-rank counts — for unequal chunk sizes.",
    visual: { archetype: "collective", params: { op: "scatter" } }, related: ["mpi_scatter", "mpi_gather"],
  },
  {
    id: "mpi_scan", tech: "MPI", category: "Collectives", name: "MPI_Scan / MPI_Exscan",
    signature: "MPI_Scan(send, recv, n, type, MPI_SUM, comm);",
    summary: "Prefix reduction: rank k receives the combined result of ranks 0..k.",
    note: "The building block of parallel prefix sums (scans).",
    visual: { archetype: "collective", params: { op: "reduce" } }, related: ["mpi_reduce", "mpi_allreduce"],
  },
  {
    id: "mpi_reduce_scatter", tech: "MPI", category: "Collectives", name: "MPI_Reduce_scatter",
    signature: "MPI_Reduce_scatter(send, recv, counts, type, MPI_SUM, comm);",
    summary: "Reduces element-wise across ranks, then scatters slices of the result to each rank.",
    visual: { archetype: "collective", params: { op: "reduce" } }, related: ["mpi_allreduce", "mpi_scatter"],
  },
  {
    id: "mpi_ibcast", tech: "MPI", category: "Collectives", name: "MPI_Ibcast (non-blocking collectives)",
    signature: "MPI_Ibcast(&buf, n, type, root, comm, &req);  MPI_Wait(&req, ..);",
    summary: "Non-blocking collectives (Ibcast/Ireduce/...): start it, compute, then complete with Wait.",
    note: "Overlap a global operation with local work, just like non-blocking point-to-point.",
    visual: { archetype: "collective", params: { op: "bcast" } }, related: ["mpi_bcast", "mpi_isend"],
  },
  {
    id: "mpi_cart_create", tech: "MPI", category: "Communicators", name: "MPI_Cart_create",
    signature: "MPI_Cart_create(comm, ndims, dims, periods, reorder, &cart);",
    summary: "Builds a Cartesian (grid) topology so ranks have natural neighbours (for stencils/halos).",
    note: "MPI_Cart_shift then gives you the neighbour ranks to exchange with.",
    visual: { archetype: "ranksMemory", params: { threads: 6, kind: "split" } }, related: ["mpi_comm_split", "mpi_sendrecv"],
  },
  {
    id: "mpi_type_vector", tech: "MPI", category: "Communicators", name: "MPI_Type_contiguous / MPI_Type_vector",
    signature: "MPI_Type_vector(count, blocklen, stride, MPI_INT, &t);\nMPI_Type_commit(&t);",
    summary: "Derived datatypes describe non-contiguous data (e.g. a column/halo) so you can send it in one call.",
    visual: { archetype: "pointToPoint", params: { mode: "blocking" } }, related: ["mpi_send", "mpi_sendrecv"],
  },
  {
    id: "mpi_abort", tech: "MPI", category: "Setup", name: "MPI_Abort",
    signature: "MPI_Abort(MPI_COMM_WORLD, errcode);",
    summary: "Forcibly terminates all ranks in the communicator — for unrecoverable errors.",
    visual: { archetype: "ranksMemory", params: { threads: 4 } }, related: ["mpi_init"],
  },

  /* ===================== OpenACC ===================== */
  {
    id: "acc_parallel", tech: "OpenACC", category: "Compute", name: "#pragma acc parallel",
    signature: "#pragma acc parallel [clauses]\n{ /* runs on the accelerator */ }",
    summary: "Launches the region on the accelerator (GPU); you control the parallelism explicitly.",
    note: "You decide gang/worker/vector. Compare with `kernels`, where the compiler decides.",
    visual: { archetype: "offload", params: { kind: "parallel" } }, related: ["acc_kernels", "acc_parallel_loop", "acc_loop"],
  },
  {
    id: "acc_kernels", tech: "OpenACC", category: "Compute", name: "#pragma acc kernels",
    signature: "#pragma acc kernels\n{ for (...) ...; for (...) ...; }",
    summary: "Hands a region to the compiler, which finds the parallel loops and offloads them.",
    note: "Easier to start with; `parallel` gives you more control when the compiler is too cautious.",
    visual: { archetype: "offload", params: { kind: "kernels" } }, related: ["acc_parallel"],
  },
  {
    id: "acc_parallel_loop", tech: "OpenACC", category: "Compute", name: "#pragma acc parallel loop",
    signature: "#pragma acc parallel loop\nfor (i = 0; i < N; i++) work(i);",
    summary: "The common combo: launch on the device and distribute the loop across it.",
    visual: { archetype: "offload", params: { kind: "loop" } }, related: ["acc_parallel", "acc_loop", "omp_parallel_for"],
  },
  {
    id: "acc_loop", tech: "OpenACC", category: "Compute", name: "#pragma acc loop",
    signature: "#pragma acc loop [gang|worker|vector] [independent]\nfor (...) ...",
    summary: "Distributes a loop's iterations across the device's parallelism levels.",
    visual: { archetype: "gangs", params: { level: "gang" } }, related: ["acc_gang", "acc_independent"],
  },
  {
    id: "acc_routine", tech: "OpenACC", category: "Compute", name: "#pragma acc routine",
    signature: "#pragma acc routine seq\ndouble f(double x) { ... }",
    summary: "Marks a function so it can be compiled for and called from device code.",
    visual: { archetype: "offload", params: { kind: "routine" } }, related: ["acc_parallel"],
  },
  {
    id: "acc_data", tech: "OpenACC", category: "Data", name: "#pragma acc data",
    signature: "#pragma acc data copy(a[0:N])\n{ /* several kernels reuse a on the device */ }",
    summary: "Opens a data region so arrays stay on the device across multiple kernels.",
    note: "The #1 OpenACC performance fix: hoist data movement out of the compute loops.",
    visual: { archetype: "accData", params: { clause: "copy" } }, related: ["acc_copyin", "acc_copyout", "acc_present"],
  },
  {
    id: "acc_copyin", tech: "OpenACC", category: "Data", name: "copyin(a[0:N])",
    signature: "#pragma acc parallel loop copyin(a[0:N])",
    summary: "Copies data host → device on entry (read-only input that the device needs).",
    visual: { archetype: "accData", params: { clause: "copyin" } }, related: ["acc_copyout", "acc_copy"],
  },
  {
    id: "acc_copyout", tech: "OpenACC", category: "Data", name: "copyout(a[0:N])",
    signature: "#pragma acc parallel loop copyout(a[0:N])",
    summary: "Copies data device → host on exit (results produced on the device).",
    visual: { archetype: "accData", params: { clause: "copyout" } }, related: ["acc_copyin", "acc_copy"],
  },
  {
    id: "acc_copy", tech: "OpenACC", category: "Data", name: "copy(a[0:N])",
    signature: "#pragma acc data copy(a[0:N])",
    summary: "Copies in on entry and out on exit — for data both read and written on the device.",
    visual: { archetype: "accData", params: { clause: "copy" } }, related: ["acc_copyin", "acc_copyout"],
  },
  {
    id: "acc_create", tech: "OpenACC", category: "Data", name: "create(tmp[0:N])",
    signature: "#pragma acc data create(tmp[0:N])",
    summary: "Allocates device memory with no transfer — for scratch/temporary arrays.",
    visual: { archetype: "accData", params: { clause: "create" } }, related: ["acc_copy", "acc_present"],
  },
  {
    id: "acc_present", tech: "OpenACC", category: "Data", name: "present(a[0:N])",
    signature: "#pragma acc parallel loop present(a[0:N])",
    summary: "Asserts the data is already on the device (from an enclosing data region) — no copy.",
    visual: { archetype: "accData", params: { clause: "present" } }, related: ["acc_data", "acc_enter_data"],
  },
  {
    id: "acc_enter_data", tech: "OpenACC", category: "Data", name: "#pragma acc enter data / exit data",
    signature: "#pragma acc enter data copyin(a[0:N])\n/* ... */\n#pragma acc exit data copyout(a[0:N])",
    summary: "Unstructured data lifetime: put data on the device now, take it off later (not block-scoped).",
    visual: { archetype: "accData", params: { clause: "copyin" } }, related: ["acc_data", "acc_update"],
  },
  {
    id: "acc_update", tech: "OpenACC", category: "Data", name: "#pragma acc update",
    signature: "#pragma acc update device(a[0:N])\n#pragma acc update self(a[0:N])   // self = host",
    summary: "Re-synchronizes the host and device copies of data without leaving the data region.",
    visual: { archetype: "accData", params: { clause: "update" } }, related: ["acc_data"],
  },
  {
    id: "acc_gang", tech: "OpenACC", category: "Parallelism levels", name: "gang",
    signature: "#pragma acc loop gang",
    summary: "Coarsest level — independent blocks of work (≈ CUDA thread blocks / MPI-like).",
    visual: { archetype: "gangs", params: { level: "gang" } }, related: ["acc_worker", "acc_vector"],
  },
  {
    id: "acc_worker", tech: "OpenACC", category: "Parallelism levels", name: "worker",
    signature: "#pragma acc loop worker",
    summary: "Middle level — a group of threads within a gang.",
    visual: { archetype: "gangs", params: { level: "worker" } }, related: ["acc_gang", "acc_vector"],
  },
  {
    id: "acc_vector", tech: "OpenACC", category: "Parallelism levels", name: "vector",
    signature: "#pragma acc loop vector",
    summary: "Finest level — SIMD lanes within a worker (≈ CUDA threads in a warp).",
    visual: { archetype: "gangs", params: { level: "vector" } }, related: ["acc_gang", "acc_worker"],
  },
  {
    id: "acc_num_gangs", tech: "OpenACC", category: "Parallelism levels", name: "num_gangs / vector_length",
    signature: "#pragma acc parallel num_gangs(256) vector_length(128)",
    summary: "Tunes how many gangs and how wide the vector lanes are for the launch.",
    visual: { archetype: "gangs", params: { level: "gang" } }, related: ["acc_gang", "acc_vector"],
  },
  {
    id: "acc_reduction", tech: "OpenACC", category: "Compute", name: "reduction(op:var)",
    signature: "#pragma acc parallel loop reduction(+:sum)",
    summary: "Combines a per-iteration value into one result (sum, max, ...) — same idea as OpenMP.",
    visual: { archetype: "reduction", params: { threads: 4 } }, related: ["omp_reduction", "mpi_reduce"],
  },
  {
    id: "acc_async", tech: "OpenACC", category: "Compute", name: "async / #pragma acc wait",
    signature: "#pragma acc parallel loop async(1)\n#pragma acc wait(1)",
    summary: "Launches device work asynchronously so the host keeps going; `wait` synchronizes.",
    note: "Overlap host work or other kernels with the device — the OpenACC analog of MPI non-blocking.",
    visual: { archetype: "offload", params: { kind: "wait" } }, related: ["mpi_isend"],
  },
  {
    id: "acc_collapse", tech: "OpenACC", category: "Compute", name: "collapse(n)",
    signature: "#pragma acc parallel loop collapse(2)\nfor (i..) for (j..) work(i,j);",
    summary: "Merges n nested loops into one big iteration space — more parallelism for the device.",
    visual: { archetype: "gangs", params: { level: "gang" } }, related: ["acc_loop", "omp_collapse"],
  },
  {
    id: "acc_independent", tech: "OpenACC", category: "Compute", name: "independent",
    signature: "#pragma acc loop independent",
    summary: "Tells the compiler the iterations are independent, so it can parallelize freely.",
    visual: { archetype: "gangs", params: { level: "gang" } }, related: ["acc_loop"],
  },
  {
    id: "acc_default_present", tech: "OpenACC", category: "Data", name: "default(present)",
    signature: "#pragma acc parallel loop default(present)",
    summary: "Assumes every array is already on the device — catches missing data clauses as errors.",
    note: "A good discipline once you manage data with explicit data regions.",
    visual: { archetype: "accData", params: { clause: "present" } }, related: ["acc_present", "acc_data"],
  },
  {
    id: "acc_cache", tech: "OpenACC", category: "Data", name: "#pragma acc cache",
    signature: "#pragma acc cache(a[i-1:3])",
    summary: "Hints that a small slice should be kept in fast on-chip memory for the loop.",
    visual: { archetype: "accData", params: { clause: "present" } }, related: ["acc_loop"],
  },
  {
    id: "acc_host_data", tech: "OpenACC", category: "Data", name: "#pragma acc host_data use_device",
    signature: "#pragma acc host_data use_device(a)\n  some_cuda_library(a);",
    summary: "Exposes the device address of data so you can pass it to CUDA/library calls.",
    note: "The bridge between OpenACC-managed data and hand-written GPU libraries.",
    visual: { archetype: "accData", params: { clause: "present" } }, related: ["acc_data"],
  },
  {
    id: "acc_tile", tech: "OpenACC", category: "Parallelism levels", name: "tile(x,y)",
    signature: "#pragma acc loop tile(32,32)\nfor (i..) for (j..) ...",
    summary: "Blocks nested loops into tiles for better locality and parallel mapping.",
    visual: { archetype: "gangs", params: { level: "worker" } }, related: ["acc_collapse", "acc_loop"],
  },
  {
    id: "acc_seq", tech: "OpenACC", category: "Parallelism levels", name: "seq",
    signature: "#pragma acc loop seq",
    summary: "Runs this loop sequentially on the device (no parallel distribution).",
    visual: { archetype: "gangs", params: { level: "gang" } }, related: ["acc_gang"],
  },
  {
    id: "acc_devices", tech: "OpenACC", category: "Compute", name: "acc_get_num_devices / acc_set_device_num",
    signature: "int n = acc_get_num_devices(acc_device_nvidia);\nacc_set_device_num(0, acc_device_nvidia);",
    summary: "Query how many accelerators are available and pick which one to run on.",
    visual: { archetype: "offload", params: { kind: "parallel" } }, related: ["acc_parallel"],
  },
];

export const TECHS: Tech[] = ["OpenMP", "MPI", "OpenACC"];
export const categoriesFor = (tech: Tech) =>
  Array.from(new Set(ENTRIES.filter((e) => e.tech === tech).map((e) => e.category)));
